name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.0"
          
      - name: Build
        run: hugo --log -v
        working-directory: "page/"

      - uses: actions/upload-artifact@v3
        with:
          name: blog
          path: page/public/
#
#  deploy-prod:
#    runs-on: 'ubuntu-latest'
#    environment: 'Prod'
#    needs: [ build ]
#    steps:
#      - name: Deploy
#        id: deploy
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
#          action: "upload"
#          app_location: "/page/" 
#          api_location: "" 
#          output_location: "public" 
#          deployment_environment: staging
#          skip_app_build: true
#          skip_api_build: true
#          verbose: true
#          workingDirectory: $(System.ArtifactsDirectory)/drop
