languageCode = "en-us"
title = "Radek Maziarka - Think. Plan. Execute. Repeat."
defaultContentLanguage  = "pl"
disqusShortname = "radekmaziarka-pl"
googleAnalytics = "UA-51551522-2"
baseURL = "https://radekmaziarka.pl/"
paginate = 10
paginatePath = "page"

[params]
  author = "Radek Maziarka"
  
[taxonomies]
  category = "category"
  tag = "tags"

[languages]
  [languages.pl]
    title = "Radek Maziarka"
    description = "Radek Maziarka - blog prywatny"
    contentDir = "content/pl"
    weight = 1     
  [languages.en]
    title = "Radek Maziarka"
    description = "Radek Maziarka - personal blog"
    contentDir = "content/en"
    weight = 2
    
  [languages.pl.permalinks]
    post = "blog/:slug"

[[languages.pl.menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 10
  
[[languages.pl.menu.main]]
  identifier = "shop"
  name = "Sklep"
  url = "/sklep"
  weight = 15
  
[[languages.pl.menu.main]]
  identifier = "szkolenia"
  name = "Szkolenia i warsztaty"
  url = "/szkolenia-i-warsztaty"
  weight = 20
  
[[languages.pl.menu.main]]
  identifier = "konsultacje"
  name = "Konsultacje"
  url = "/konsultacje"
  weight = 20
 
  
[[languages.pl.menu.main]]
  identifier = "o-mnie"
  name = "O mnie"
  url = "/o-mnie"
  weight = 80


[[languages.pl.menu.main]]
  identifier = "kontakt"
  name = "Kontakt"
  url = "/kontakt"
  weight = 90
  
[[languages.en.menu.main]]
  identifier = "main"
  name = "Main Page"
  url = "/en"
  weight = 10

[[languages.en.menu.main]]
  identifier = "about-me"
  name = "About me"
  url = "/about-me"
  weight = 20

[[languages.en.menu.main]]
  identifier = "design-patterns"
  name = "Design patterns"
  url = "/en/category/design-patterns"
  weight = 30


[[languages.en.menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 40

[[languages.en.menu.main]]
  identifier = "polish-posts"
  name = ""
  url = "/"
  weight = 50

