languageCode = "en-us"
title = "Radek Maziarka - I solve problems"
defaultContentLanguage  = "pl"
disqusShortname = "radekmaziarka-pl"
googleAnalytics = "UA-51551522-2"
baseURL = "https://radekmaziarka.pl/"
paginate = 10
paginatePath = "page"

[params]
  author = "Radek Maziarka"

[taxonomies]
  category = "category"
  tag = "tags"

[languages]
  [languages.pl]
    title = "Radek Maziarka"
    description = "Radek Maziarka - blog prywatny"
    contentDir = "content/pl"
    weight = 1     
  [languages.en]
    title = "Radek Maziarka"
    description = "Radek Maziarka - personal blog"
    contentDir = "content/en"
    weight = 2

[[languages.pl.menu.main]]
  identifier = "main"
  name = "Strona główna"
  url = "/"
  weight = 10

[[languages.pl.menu.main]]
  identifier = "category-leadership"
  name = "Narzędzia pracy konsultanta"
  url = "/2020/02/04/narzedzia-pracy-konsultanta-podsumowanie/"
  weight = 20
  
[[languages.pl.menu.main]]
  identifier = "szkolenia"
  name = "Szkolenia i warsztaty"
  url = "/szkolenia-i-warsztaty"
  weight = 40

[[languages.pl.menu.main]]
  identifier = "o-mnie"
  name = "O mnie"
  url = "/o-mnie"
  weight = 50
  
[[languages.pl.menu.main]]
  identifier = "kontakt"
  name = "Kontakt"
  url = "/kontakt"
  weight = 60

[[languages.pl.menu.main]]
  identifier = "o-mnie-prelekcje"
  name = "Prelekcje"
  url = "/prelekcje"
  weight = 10
  parent = "o-mnie"

[[languages.pl.menu.main]]
  identifier = "english-posts"
  name = "English site"
  url = "/en"
  weight = 70
  
[[languages.en.menu.main]]
  identifier = "main"
  name = "Main Page"
  url = "/en"
  weight = 10

[[languages.en.menu.main]]
  identifier = "about-me"
  name = "About me"
  url = "/about-me"
  weight = 20

[[languages.en.menu.main]]
  identifier = "design-patterns"
  name = "Design patterns"
  url = "/en/category/design-patterns"
  weight = 30


[[languages.en.menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 40

[[languages.en.menu.main]]
  identifier = "polish-posts"
  name = "Strona polska"
  url = "/"
  weight = 50

