trigger:
- master

stages:
# build stage: build site codebase to use for deployment
- stage: Build
  jobs:
    - template: /infra/ado/build.yaml
      parameters:
        hugoVersion: '0.91.2'
        blogPath: './page'
      
- stage: Prod_Release
  variables:
      - group: Prod
  jobs:
    - template: /infra/ado/release.yaml
      parameters:
        environmentName: 'Prod'