pool:
  vmImage: "ubuntu-16.04"

variables:
  hugo.version: '0.67.1'
  blog.path: './page'

steps:
- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
  displayName: "Download HUGO"

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: "Install HUGO"

- script: |
   cd $(blog.path)
   hugo --log -v
  displayName: 'Generate Blog'

- task: PublishPipelineArtifact@0
  displayName: Publish Blog
  inputs:
    targetPath: '$(blog.path)/public'
    artifactName: $(Build.BuildId)
    publishLocation: 'Container'