parameters:
- name: hugoVersion
  type: string
  default: false
- name: blogPath
  type: string
  default:

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      wget -c https://github.com/gohugoio/hugo/releases/download/v${{parameters.hugoVersion}}/hugo_${{parameters.hugoVersion}}_Linux-64bit.deb
    displayName: "Download HUGO"

  - script: 'sudo dpkg -i hugo_${{parameters.hugoVersion}}_Linux-64bit.deb'
    displayName: "Install HUGO"

  - script: |
      cd ${{parameters.blogPath}}
      hugo --log -v
    displayName: 'Generate Blog'

  - task: PublishPipelineArtifact@0
    displayName: Publish Blog
    inputs:
      targetPath: '${{parameters.blogPath}}/public'
      artifactName: $(Build.BuildId)
      publishLocation: 'Container'