trigger:
- master

stages:
# build stage: build site codebase to use for deployment
- stage: build
  jobs:
    - template: /infra/ci-cd/build.yaml
      parameters:
        hugoVersion: '0.67.1'
        blogPath: './page'
      
- stage: release Test
  jobs:
    - template: /infra/ci-cd/release.yaml
      parameters:
        azureSubscription: 'radekmaziarka-test'
        storageAccountName: 'radekmaziarkateststorage'

- stage: release Prod
  jobs:
    - template: /infra/ci-cd/release.yaml
      parameters:
        azureSubscription: 'radekmaziarka-prod'
        storageAccountName: 'radekmaziarkaprodstorage'