trigger:
- master

stages:
# build stage: build site codebase to use for deployment
- stage: build
  jobs:
    - template: /infra/ci-cd/build.yaml
      parameters:
        hugoVersion: '0.67.1'
        blogPath: './page'
      
- stage: release
  jobs:
    - template: /infra/ci-cd/release.yaml