trigger:
- master

stages:
# build stage: build site codebase to use for deployment
- stage: build
  jobs:
    - template: /infra/ci-cd/build.yaml
      parameters:
        'hugo.version': '0.67.1'
        'blog.path': './page'
      
- stage: release
  jobs:
    - template: /infra/ci-cd/release.yaml