jobs:
- job: release_test
  pool:
    vmImage: windows-latest
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: $(Build.BuildId)
      path: $(Build.SourcesDirectory)/bin

  - task: AzureFileCopy@4
    inputs:
      sourcePath: $(Build.SourcesDirectory)/bin
      azureSubscription: 'radekmaziarka.pl-test'
      destination: azureBlob
      storage: radekmaziarkateststorage
      containerName: $web