parameters:
  azureSubscription: ""
  storageAccountName: ""
  environmentName: ""

jobs:
- job: release_to_azure_storage
  environment: ${{ parameters.environmentName }}
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: $(Build.BuildId)
      path: $(Build.SourcesDirectory)/bin

  - task: AzureCLI@1
    displayName: 'Azure CLI: copy files to storage'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptLocation: inlineScript
      inlineScript: |
         az storage blob upload-batch --destination \$web --source $(Build.SourcesDirectory)/bin --account-name ${{ parameters.storageAccountName }}