parameters:
  azureSubscription: ""
  storageAccountName: ""
  environmentName: ""

jobs:
- deployment: release_to_azure_storage
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: $(Build.BuildId)
            path: $(Build.SourcesDirectory)/bin

        - task: AzureCLI@1
          displayName: 'Azure CLI: remove (almost) everything'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptLocation: inlineScript
            inlineScript: |
              az storage blob delete-batch --source \$web --account-name ${{ parameters.storageAccountName }} --pattern "[!robots.txt]"

        - task: AzureCLI@1
          displayName: 'Azure CLI: copy files to storage'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptLocation: inlineScript
            inlineScript: |
              az storage blob upload-batch --destination \$web --source $(Build.SourcesDirectory)/bin --account-name ${{ parameters.storageAccountName }}