jobs:
- job: release_test
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: $(Build.BuildId)
      path: $(Build.SourcesDirectory)/bin

  - task: AzureCLI@1
    displayName: 'Azure CLI: copy files to storage'
    inputs:
      azureSubscription: 'radekmaziarka.pl-test'
      scriptLocation: inlineScript
      inlineScript: |
         az storage blob upload-batch --destination "$web" 
         --source $(Build.SourcesDirectory)/bin --account-name radekmaziarkateststorage

  - task: AzureCLI@1
    displayName: 'Azure CLI: Purge CDN'
    inputs:
      azureSubscription: 'radekmaziarka.pl-test'
      scriptLocation: inlineScript
      inlineScript: |
        call az cdn endpoint purge  -g radekmaziarka-test -n radekmaziarka-test 
        --profile-name radekmaziarka-test --content-paths "/*"