jobs:
- job: release_test
  pool:
    vmImage: windows-latest
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: $(Build.BuildId)
      path: $(Build.SourcesDirectory)/bin

  - task: AzureFileCopy@4
    inputs:
      sourcePath: $(Build.SourcesDirectory)/bin
      azureSubscription: 'radekmaziarka.pl-test'
      destination: azureBlob
      storage: radekmaziarkateststorage
      containerName: $web

  - task: AzureCLI@1
    displayName: 'Azure CLI: Purge CDN'
    inputs:
      azureSubscription: 'radekmaziarka.pl-test'

      scriptLocation: inlineScript

      inlineScript: |
        call az cdn endpoint purge  -g radekmaziarka-test -n radekmaziarka-test --profile-name radekmaziarka-test --content-paths "/*"