baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[permalinks]
  posts = "/:slug"
  pages = "/:slug"

[taxonomies]
  category = "category"
  tag = "tags"

[menu]

[[menu.main]]
  identifier = "main"
  name = "Strona główna"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "category/leadership"
  name = "Leadership"
  url = "/category/leadership/"
  weight = 20

[[menu.main]]
  identifier = "category/wzorce-projektowe"
  name = "Wzorce projektowe"
  url = "/category/wzorce-projektowe/"
  weight = 30

[[menu.main]]
  identifier = "szkolenia"
  name = "Szkolenia"
  url = "/szkolenia"
  weight = 40

[[menu.main]]
  identifier = "szkolenia/techniczne"
  name = "Techniczne"
  url = "/szkolenia/techniczne"
  weight = 0
  parent = "szkolenia"

[[menu.main]]
  identifier = "o-mnie"
  name = "O mnie"
  url = "/o-mnie"
  weight = 50

[[menu.main]]
  identifier = "o-mnie/prelekcje"
  name = "Prelekcje"
  url = "/prelekcje"
  weight = 10
  parent = "o-mnie"

  
[[menu.main]]
  identifier = "o-mnie/kontakt"
  name = "Kontakt"
  url = "/kontakt"
  weight = 20
  parent = "o-mnie"